files_test = [size(trmm_filenames, 1) > 0, size(tmi_filenames, 1) > 0, size(cs_filenames, 1) > 0, size(amsre_filenames, 1) > 0];
fprintf('Test get files %d %d %d %d: %d\n',...
    files_test(1), files_test(2), files_test(3), files_test(4),...
    sum(files_test) == 4);


cs_trmm_int_test = size(intersections, 2);
fprintf('Test find CS-TRMM intersections %d: %d\n',...
        cs_trmm_int_test,...
        cs_trmm_int_test > 0 & mod(cs_trmm_int_test, 2) == 0);